name: Build Wanix
on: [push]

jobs:
  linux:
    name: Linux
    uses: tractordev/wanix/.github/workflows/build-linux.yml@main
    permissions:
      contents: read
      packages: write
    with:
      artifact-name: linux
      path: external/linux

  v86:
    name: v86
    uses: tractordev/wanix/.github/workflows/build-v86.yml@main
    permissions:
      contents: read
      packages: write
    with:
      artifact-name: v86
      path: external/v86
  
  shell:
    name: Shell
    uses: tractordev/wanix/.github/workflows/build-shell.yml@main
    permissions:
      contents: read
      packages: write
    with:
      artifact-name: shell
      path: shell
  
  js:
    name: JavaScript
    uses: tractordev/wanix/.github/workflows/build-js.yml@main
    permissions:
      contents: read
      packages: write
    with:
      artifact-name: js
      path: runtime

  build:
    name: Build Wanix
    needs: [linux, v86, shell, js]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download v86 artifact
        uses: actions/download-artifact@v4
        with:
          name: v86
          path: external/v86
      
      - name: Download Linux kernel artifact
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: external/linux
      
      - name: Download shell artifact
        uses: actions/download-artifact@v4
        with:
          name: shell
          path: shell

      - name: Download JavaScript artifact
        uses: actions/download-artifact@v4
        with:
          name: js
          path: runtime/assets

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true

      - name: Set up TinyGo
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.38.0/tinygo_0.38.0_amd64.deb
          sudo dpkg -i tinygo_0.38.0_amd64.deb

      - name: Build TinyGo WASM and Wanix command
        run: |
          make wasm-tinygo cmd
          mv .local/bin/wanix wanix
          mv runtime/assets/wanix.wasm wanix.wasm
      
      - uses: actions/upload-artifact@v4
        with:
          name: wanix-tinygo-linux-amd64
          path: |
            wanix.wasm
            wanix

      - name: Build (Big) Go WASM and Wanix command
        run: |
          make wasm-go cmd
          mv .local/bin/wanix wanix
          mv runtime/assets/wanix.wasm wanix.wasm
      
      - uses: actions/upload-artifact@v4
        with:
          name: wanix-go-linux-amd64
          path: |
            wanix.wasm
            wanix
      
      
